# Thanks to Beafantles for this file (https://github.com/Beafantles/Discode/tree/master/data/code)!

LANGUAGES_FILES_EXTENSIONS = {
    "Bash": ["sh"],
    "C": ["c", "h"],
    "C#": ["cs"],
    "C++": ["cc", "cpp", "cp", "cxx", "cbp", "hh", "hpp", "hxx", "inl"],
    "CoffeeScript": ["coffee", "litcoffee"],
    "Crystal": ["cr", "ecr", "slang"],
    "D": ["d"],
    "Elixir": ["exs", "ex"],
    "Erlang": ["erl", "hrl"],
    "F#": ["fs", "fsi", "fsx", ".fsscript"],
    "Go": ["go"],
    "Groovy": ["groovy"],
    "Haskell": ["hs", "has", "lhs", "lit"],
    "Java": ["java", "class", "jar", "war"],
    "JavaScript": ["js"],
    "Lazy_K": ["lazy"],
    "Lisp": ["lisp", "lsp", "l", "cl", "fasl"],
    "Lua": ["lua", "luc"],
    "Nim": ["nim"],
    "OCaml": ["ml", "mli"],
    "Pascal": ["pas", "pp", "p", "inc", "tpu"],
    "Perl": ["pl", "pm", "ph", "pod"],
    "PHP": ["php", "php3", "php4", "php5", "phps", "phtml"],
    "Pony": ["", "pony"],
    "Python": ["py", "pyc", "pyo", "pyd", "pyw", "rpy"],
    "Rill": ["rill"],
    "Ruby": ["rb", "erb", "rbw"],
    "Rust": ["rs", "rlib"],
    "Scala": ["scala", "sc"],
    "SQL": ["sql", "eql"],
    "Swift": ["swift"],
    "Vim": ["vim"],
}

LANGUAGES_IDENTIFIERS = {
    "Bash": ["bash", "sh"],
    "C": ["c"],
    "C#": ["cs", "csharp"],
    "C++": ["cpp"],
    "CoffeeScript": ["coffeescript"],
    "Crystal": ["crystal"],
    "D": ["d"],
    "Elixir": ["elixir"],
    "Erlang": ["erlang"],
    "F#": ["fsharp"],
    "Go": ["go"],
    "Groovy": ["groovy"],
    "Haskell": ["haskell"],
    "Java": ["java"],
    "JavaScript": ["js", "javascript"],
    "Lazy_K": ["k", "lazy_k"],
    "Lisp": ["lisp"],
    "Lua": ["lua"],
    "Nim": ["nim", "nimrod"],
    "OCaml": ["ocaml"],
    "Pascal": ["pascal"],
    "Perl": ["perl"],
    "PHP": ["php"],
    "Pony": ["pony"],
    "Python": ["py", "python"],
    "Rill": ["rill"],
    "Ruby": ["ruby"],
    "Rust": ["rust"],
    "Scala": ["scala"],
    "SQL": ["sql"],
    "Swift": ["swift"],
    "Vim": ["vim"],
}

LANGUAGES_IMAGES = {
    "Bash": "https://i.imgur.com/Fx9vZGc.png",
    "C": "https://png.icons8.com/color/1600/c-programming.png",
    "C#": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Csharp_Logo.png",
    "C++": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/1200px-ISO_C%2B%2B_Logo.svg.png",
    "CoffeeScript": "https://pbs.twimg.com/profile_images/557241144392708096/slQydAMv_400x400.png",
    "Crystal": "https://i.imgur.com/YzgCXSB.png",
    "D": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/D_Programming_Language_logo.svg/317px-D_Programming_Language_logo.svg.png",
    "Elixir": "https://upload.wikimedia.org/wikipedia/commons/9/92/Official_Elixir_logo.png",
    "Erlang": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Erlang_logo.svg/1200px-Erlang_logo.svg.png",
    "F#": "https://i.imgur.com/NbRNr5U.png",
    "Go": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Gogophercolor.png/480px-Gogophercolor.png",
    "Groovy": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Groovy-logo.svg/1200px-Groovy-logo.svg.png",
    "Haskell": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Haskell-Logo.svg/640px-Haskell-Logo.svg.png",
    "Java": "https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Java_programming_language_logo.svg/328px-Java_programming_language_logo.svg.png",
    "JavaScript": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/JavaScript-logo.png/480px-JavaScript-logo.png",
    "Lazy_K": "https://i.imgur.com/Myl1Wq0.png",
    "Lisp": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Lisplogo.png/484px-Lisplogo.png",
    "Lua": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Lua-logo-nolabel.svg/500px-Lua-logo-nolabel.svg.png",
    "Nim": "https://raw.githubusercontent.com/nim-lang/assets/master/Art/logo-crown.png",
    "OCaml": "https://i.imgur.com/oPMs6Ft.png",
    "Pascal": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Blaise_Pascal_Versailles.JPG/504px-Blaise_Pascal_Versailles.JPG",
    "Perl": "https://upload.wikimedia.org/wikipedia/en/0/00/Perl-camel-small.png",
    "PHP": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/PHP-logo.svg/500px-PHP-logo.svg.png",
    "Pony": "https://i.imgur.com/11TSK43.png",
    "Python": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/500px-Python-logo-notext.svg.png",
    "Rill": "https://i.imgur.com/VagH89j.png",
    "Ruby": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Ruby_logo.svg/500px-Ruby_logo.svg.png",
    "Rust": "https://www.rust-lang.org/logos/rust-logo-512x512.png",
    "Scala": "https://i.imgur.com/5uBOncQ.png",
    "SQL": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Applications-database.svg/500px-Applications-database.svg.png",
    "Swift": "https://upload.wikimedia.org/wikipedia/fr/6/63/Logo_Apple_Swift.png",
    "Vim": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Vimlogo.svg/500px-Vimlogo.svg.png",
}
