name: Ruff

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruff
        uses: astral-sh/ruff-action@v3

      - name: Run Ruff format
        run: ruff format

      - name: Run Ruff check
        run: ruff check --fix --unsafe-fixes
